 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: dotnet publish -c Release /p:Platform="x86"
       
       - run: 
          name: Compress Artifacts
          command: tar -cvf MaiksLauncher.tar C:\Users\circleci\project\test\bin\x86\Release\netcoreapp3.0\publish\
       - store_artifacts: 
           path: MaiksLauncher.tar
